image: node:latest

variables:
  DEST_DIR: dest/

# package.json が編集された時だけ npm install する
build:prod:
  stage: build
  dependencies: []
  script:
    - mkdir -p .cache
    - npm config set cache $CI_PROJECT_DIR/.cache/npm --global
    - yarn config set cache-folder $CI_PROJECT_DIR/.cache/yarn
    - >
      (test -d node_modules/ && diff .cache/package.json package.json > /dev/null 2>&1) ||
      (rm -fr node_modules/ &&
        (test -f yarn.lock && yarn install) ||
        (test -f package-lock.json && npm ci) ||
        npm install
      )
    - cp -p package.json .cache/
  cache:
    paths:
      - .cache/
      - node_modules/
  artifacts:
    paths:
      - $DEST_DIR

login_clasp:
  script:
    - ./node_modules/.bin/clasp login
